fits: 
  - {id: 260527-ac-01-ntk-sgd, label: test}

xscale: linear
yscale: log
error_type: mean
force_recompute: False

Rankspces:
  - rank_indices: [1, 2, 3, 4]
    rank_title: Test 1
  - rank_indices: [4, 5, 6, 7]
    rank_title: Test 2

template_text: |
  # NTK plots
  ---------
  {@with Rankspces@}
  ## {@rank_title@}
  {@plot_eigvals_by_fit@}
  {@endwith@}

actions_:
  - report(main=True)
